//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotesCalculator
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Candidate
    {

        public Candidate()
        {
            this.Voters = new HashSet<Voter>();
        }

        public int CandidateId { get; set; }

        [XmlElement(ElementName = "name")]
        public string Name { get; set; }

        [XmlElement(ElementName = "party")]
        public string Party { get; set; }


        [XmlIgnore]
        public virtual ICollection<Voter> Voters { get; set; }
        public bool IsChecked { get; set; }
    }
}