//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotesCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        public int VoteId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PersonalIdNumber { get; set; }
        public int CandidateId { get; set; }
    
        public virtual Candidate Candidate { get; set; }

        public Voter() { }
        public Voter(string firstName, string lastName, string personalIdNumber)
        {
            FirstName = firstName;
            LastName = lastName;
            PersonalIdNumber = personalIdNumber;
        }

    }
}
